version: '3'

services:
 database:
  container_name: mongo
  image: mongo
  ports:
   - "27017:27017"
 frontend:
  container_name: angular
  build: frontend
  ports:
   - "4200:4200"
  command: >
        bash -c "ng serve --host 0.0.0.0 --port 4200"
 backend:
  container_name: nest
  build: backend
  ports:
   - "3000:3000"
